name: Deploy skincare
on: push
jobs: 
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: dockerhub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_TOKEN}}
      - name: imagebuild
        run: docker build -t ramalakshmi79/demo:docker-image .
      - name: pushing image
        run: docker push ramalakshmi79/demo:docker-image
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - name: ec2connect
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PEMKEY }}
          HOSTNAME: ${{secrets.EC2_HOSTNAME}}
          USER_NAME: ${{secrets.EC2_USERNAME}} 
        run: |
          echo "$PRIVATE_KEY" > private_key.pem  
          chmod 600 private_key.pem   
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${USER_NAME}@${HOSTNAME} '
            docker pull ramalakshmi79/demo:docker-image
            docker stop anu1
            docker rm anu1
            docker rmi -f ramalakshmi79/demo:docker-image
            docker run -d -p  891:80 --name anu1 ramalakshmi79/demo:docker-image
            '


 


         


